fix: move binary to `/sbin`, update systemd unit, and improve URL validation
- Changed binary installation path from `/bin` to `/sbin` in `Makefile` and systemd unit.
- Added URL validation logic in the ping script to ensure valid URLs before execution.
- Suppressed curl output to `/dev/null` for cleaner logs.

diff --git a/src/bash/cronitor-ping b/src/bash/cronitor-ping
--- a/src/bash/cronitor-ping
+++ b/src/bash/cronitor-ping
@@ -11,6 +11,12 @@ else
     URL="$(< "$CREDENTIALS_DIRECTORY/cronitor.url")"
 fi
 
+# Check if url is valid
+if ! [[ "$URL" =~ ^http(s)?://.* ]]; then
+    echo "Error: invalid url" >&2
+    exit 4
+fi
+
 # Retrieve and update counter
 counter=0
 if [ -z "$RUNTIME_DIRECTORY" ]; then
@@ -46,4 +52,4 @@ curl --max-time "$MAX_TIME" \
     --get \
     --data-urlencode "msg=uptime: $UPTIME" \
     --data-urlencode "metric=count:$counter" \
-    "$URL"
+    "$URL" > /dev/null
